version: '3'
services:
  ssh-sever:
    image: linuxserver/openssh-server
    ports:
      - 2222:2222
    volumes:
      - /tmp:/tmp
    environment:
      PASSWORD_ACCESS: 'true'
      USER_NAME: 'user'
      USER_PASSWORD: 'password'
      UID: $UID
      GID: $GID

  web-driver-arm:
    image: seleniarm/standalone-chromium:4.10
    ports:
      - '4444:4444'
      - '7900:7900'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VNC_NO_PASSWORD=1

  playwright:
    image: mcr.microsoft.com/playwright:v1.50.1-noble
    ports:
      - "3000:3000"
    command: [ "npx", "-y", "playwright@1.50.1", "run-server", "--port", "3000", "--host", "0.0.0.0" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DISPLAY: web-driver-arm:99.0