ext.jacocoExcludes = [
        'org/testcharm/dal/extensions/inspector/ClientConnection.class',
        'org/testcharm/dal/extensions/inspector/HttpRequest.class',
        'org/testcharm/dal/extensions/inspector/HttpResponse.class',
        'org/testcharm/dal/extensions/inspector/HttpWsServer.class',
]

dependencies {
    implementation project(':DAL-java')

    testImplementation project(':DAL-extension-basic')
    testImplementation project(':RESTful-cucumber')
    testImplementation project(':page-flow-selenium')
    testImplementation project(':page-flow-playwright')
    testImplementation project(':java-compiler-util')
    testImplementation libs.test.awaitility
    testImplementation libs.test.slf4j.simple
}
