ext.jacocoExcludes = [
        'org/testcharm/dal/compiler/Notations<init>.class',
        'org/testcharm/dal/compiler/Notations$Operators<init>.class',
        'org/testcharm/dal/compiler/Notations$Keywords<init>.class'
]

dependencies {
    api project(':bean-util')
    api project(':interpreter-core')

    testImplementation project(':java-compiler-util')
    testImplementation libs.test.jackson.databind
}
