plugins {
    alias(libs.plugins.shadow)
}

dependencies {
    implementation libs.prod.json.org
    testImplementation project(':DAL-java')
    testImplementation project(':DAL-extension-basic')
    testImplementation project(':java-compiler-util')
}

shadowJar {
    archiveClassifier.set('')
    relocate 'org.json', 'org.testcharm.shaded.org.json'
}

jar {
    archiveClassifier.set('plain')
}
