ext.jacocoExcludes = [
        'io/cucumber/core/runtime/**',
        'io/cucumber/core/runner/**',
]

dependencies {
    implementation project(":bean-util")
    implementation libs.prod.cucumber.core
    testImplementation project(':java-compiler-util')
    testImplementation project(':DAL-extension-basic')
    testImplementation project(':jfactory-cucumber')
}
